version: '3.4'

services:
  postservice:
    image: ${DOCKER_REGISTRY-}postservice
    build:
      context: .
      dockerfile: src/PostService/Dockerfile

  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: src/UserService/Dockerfile

  rabbitmq:  
     image: rabbitmq:3-management
     container_name: rabbitmq